# Generated by Django 5.1.1 on 2024-09-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('media', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'Youtube')], default='twitch', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('on_live', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='discord_bot.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='addressee',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='member',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='discord_bot.member'),
        ),
        migrations.AddField(
            model_name='guild',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='discord_bot.channel'),
        ),
        migrations.AddField(
            model_name='guild',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='discord_bot.emoji'),
        ),
        migrations.AddField(
            model_name='live',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live', to='discord_bot.role'),
        ),
        migrations.AddField(
            model_name='guild',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guild', to='discord_bot.role'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='discord_bot.role'),
        ),
    ]
