# Generated by Django 5.1.1 on 2024-09-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0003_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
