# Generated by Django 5.1.1 on 2024-12-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0004_alter_livetwitch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetwitch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
