# Generated by Django 5.1.1 on 2024-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0004_remove_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTwitch',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('channel', models.IntegerField()),
                ('role', models.IntegerField(null=True)),
                ('background_url', models.URLField()),
                ('icon_url', models.URLField()),
                ('on_live', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='guild',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='live',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='member',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='role',
        ),
        migrations.AlterField(
            model_name='rank',
            name='guild',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='live',
            name='role',
        ),
        migrations.AlterField(
            model_name='rank',
            name='member',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Emoji',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.DeleteModel(
            name='Live',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
