# Generated by Django 5.1.1 on 2024-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0005_livetwitch_remove_guild_channel_remove_live_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.CharField(max_length=50)),
                ('member', models.CharField(max_length=50)),
                ('count', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RankVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.CharField(max_length=50)),
                ('member', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.AlterField(
            model_name='livetwitch',
            name='channel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livetwitch',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
