# Generated by Django 5.1.1 on 2024-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0006_rankchat_rankvoice_delete_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankchat',
            name='count',
            field=models.IntegerField(),
        ),
    ]
