# Generated by Django 5.1.1 on 2024-10-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_bot', '0008_livetwitch_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetwitch',
            name='background_url',
            field=models.URLField(null=True),
        ),
    ]
