# Generated by Django 5.1.1 on 2024-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50, null=True)),
                ('background', models.URLField(null=True)),
                ('icon', models.URLField()),
                ('emoji_prefix', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
