# Generated by Django 5.1.1 on 2024-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch_bot', '0003_alter_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
